### ISSUE TITLE
Question about the speed

### ISSUE THREAD

**Issue by PaulEdeline2** [amsikking/thorlabs_MCM3000#1]
Hi,

Thank you a lot for your job, I'm working on thorlabs MCM3000 too and this could be really helpful for me.
I just have a quick question : do you thing controlling the speed of the movements remotely is possible ? I didn't find any solution to do it, while it is possible using the manual controller.

Thanks again,
Paul

**Comment by amsikking** [comment]
I believe the speed is controlled only by the physical 'knob' on top of the 3-axis controller (it's feels like a potentiometer).  See the user manual page 23 (MCM3000 Series Chapter 6: Maintaining the MCM3000 Series, TTN020441-D02):

"_Problem_ - Stage Moving Too Slow. _Solution_ -  Check the Speed Control knob on the 3-Axis Controller Knob. **Software cannot control the speed of the stage**."

**Comment by PaulEdeline2** [comment]
Yes that's what I was afraid of.  The fact that the speed of the physical knob is uncorrelated with the remote speed control is kinda annoying..

Thanks for your help !
