### ISSUE TITLE
 'MMP-2XY' stage

### ISSUE THREAD

**Issue by ThomasVermoesenPsiQ** [amsikking/thorlabs_MCM3000#2]
Hi your code works great! I thought I would add a the parameters for the stage I used:

   supported_stages = { # 'Type': (_um_per_count, +- _position_limit_um, )
            'ZFM2020':( 0.2116667, 1e3 * 12.7),
            'ZFM2030':( 0.2116667, 1e3 * 12.7),
            'MMP-2XY':(0.5, 1e3 * 25.4)}

**Comment by ThomasVermoesenPsiQ** [comment]
supported_stages = { # 'Type': (_um_per_count, +- _position_limit_um, )
'ZFM2020':( 0.2116667, 1e3 * 12.7),
'ZFM2030':( 0.2116667, 1e3 * 12.7),
'MMP-2XY':(0.5, 1e3 * 25.4)}

**Comment by amsikking** [comment]
Hi Thomas, thanks for your contribution!
