### ISSUE TITLE
Guidance on adding a new stage

### ISSUE THREAD

**Issue by richbai90** [amsikking/thorlabs_MCM3000#4]
I'm trying to add support for the PLS-XY stage, but I can't figure out what to set for the maximum position value. Where can I find this information?

**Comment by amsikking** [comment]
Looks like the total travel range is 25.4mm (https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=8567). So how about +-12.7mm?

**Comment by richbai90** [comment]
Okay, that's what I thought. The problem I'm having is that I cannot make any relative movements because the controller is returning values for the current position that when converted to um exceed the travel range. I've built a very simple command interface for controlling the device and enabled very verbose mode. Here's what I'm seeing:

```
Enter a command: connect
Multiple serial ports found select one by its index:
0. COM1 (Communications Port (COM1))
1. COM32 (MCM3000 (COM32))
Select a serial port: 1
Using serial port COM32.
MCM3000: opening... done.
MCM3000(ch0): getting encoder counts
MCM3000(ch0): sending cmd: b'\n\x04\x00\x00\x00\x00'
MCM3000(ch0): -> response: b'\x0b\x04\x06\x00\x00\x00\x00\x00\xf4\xa8\xfd\xff'
MCM3000(ch0): -> encoder counts = -153356
MCM3000(ch0): -> encoder counts -153356 = -32460.36um
MCM3000(ch1): getting encoder counts
MCM3000(ch1): sending cmd: b'\n\x04\x01\x00\x00\x00'
MCM3000(ch1): -> response: b'\x0b\x04\x06\x00\x00\x00\x01\x001\x15\xac\x16'
MCM3000(ch1): -> encoder counts = 380376369
MCM3000(ch1): -> encoder counts 380376369 = 80513010.78um
MCM3000: stages: ('PLS-XY', 'PLS-XY', None)
MCM3000: reverse: (False, False, False)
MCM3000: um_per_count: [0.2116667, 0.2116667, None]
MCM3000: position_limit_um: [12700.0, 12700.0, None]
MCM3000: position_um: [-32460.358445200003, 80513010.7842123, None]
Connected to MCM3000 on serial port COM32.
Enter a command: left 100
MCM3000(ch0): requested move_um = -100.00 (relative=True)
Failed to move stage: MCM3000: ch0 -> move_um (-32560.36) exceeds position_limit_um (12700.00)
```

**Comment by amsikking** [comment]
I don't have the PLS-XY so I can't debug directly. However, based on what you're seeing, perhaps you need to 'zero' the encoder at the center of the range? For example, use the Thorlabs GUI to put the stages in the middle of their total range (so they can move +-12.7mm each way), then call 'controller._set_encoder_counts_to_zero(channel)' in Python?

**Comment by edwardando** [comment]
Hi there,
Great work, lovely and clean and not over-engineered.

I'd like to hijack this thread for the integration of a simpler PLS-X stage.
Using "ZFM2020" seems to be OK but would be happy to contribute correct  (_um_per_count, +- _position_limit_um, ) values with some testing on our side at EPFL.
Does the advice above hold?

**Comment by amsikking** [comment]
Hi, thanks for the feedback! Yes I believe the above information is correct. Good luck with the testing!

**Comment by richbai90** [comment]
Sorry for abandoning this thread. The problem was resolved with a firmware update. The "ZFM2020" values work well enough for what I'm doing but I'd be happy to see what @edwardando comes up with.
