### ISSUE TITLE
Where did you find documentation?

### ISSUE THREAD

**Issue by williamc96** [amsikking/thorlabs_MCM3000#7]
Hi @amsikking great code and thanks for sharing. I'm wondering where you found the documentation for what commands to send e.g. for move:
     cmd = b'\x53\x04\x06\x00\x00\x00' + channel_bytes + encoder_bytes
 
 I can't find the information anywhere online or in the SDK.h that comes with the software download. I'm trying to see if there's a way to zero the position with a different command (or use the setParams function from the SDK)
 long SetParam(const long paramID, const double param);

/*! \fn long GetParam(const long paramID, double &param)
    \brief Gets a parameter value
	\param paramID Unique ID of the parameter to retrieve
    \param param Current value of the parameter
	\return If the function succeeds the return value is TRUE.
	\example MCM3000PositionTest.cpp
*/

Thanks!
Will

**Comment by amsikking** [comment]
Hi @williamc96, 

it's been a few years so I don't remember much. I included a minimal [.pdf](https://github.com/amsikking/thorlabs_MCM3000/blob/main/MCM3000_Direct_Serial_Communication.pdf) with commands which I think I got directly from Thorlabs by email at the time (maybe ask them again for an updated version?). For other commands I probably just tried things from the Thorlabs APT protocol ([here's a version](https://github.com/amsikking/thorlabs_DDS050/blob/main/APT_Communications_Protocol.pdf)).

I hope that helps, Alfred.

**Comment by williamc96** [comment]
Awesome thanks so much!
